[package]
name = "ws_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws_protocol = { path = "../ws_protocol" }
ctrlc = "3.2.4"
